Repository googleapis/java-pubsub-group-kafka-connector, pull requests merged in 2022-09, with the labels that each got.

#96 test: Add tests for CPS source connector, PSL sink and source connectors
  pom.xml
  src/main/java/com/google/pubsublite/kafka/sink/Constants.java
  src/main/java/com/google/pubsublite/kafka/sink/PublisherFactoryImpl.java
  src/main/resources/log4j.properties
  src/test/java/it/Base.java
  src/test/java/it/StandaloneIT.java
  src/test/resources/cps-source-connector-test.properties
  src/test/resources/kafka_vm_startup_script.sh
  src/test/resources/log4j.properties
  src/test/resources/pubsub-lite-sink-connector-test.properties
  src/test/resources/pubsub-lite-source-connector-test.properties
Labels: size: l

#122 chore: Fix download URL and bump to 3.2.3
  README.md
  config/cps-sink-connector.properties
  config/cps-source-connector.properties
  config/pubsub-lite-sink-connector.properties
  config/pubsub-lite-source-connector.properties
  copy_tool.py
  src/test/java/it/Base.java
  src/test/resources/cps-sink-connector-test.properties
  src/test/resources/kafka_vm_startup_script.sh
Labels: size: l

#127 deps: update pom.xml
  pom.xml
Labels: size: s

#123 docs: readme (quickstart) and other misc
  README.md
  config/cps-sink-connector.properties
  config/cps-source-connector.properties
  config/pubsub-lite-sink-connector.properties
  config/pubsub-lite-source-connector.properties
  copy_tool.py
  src/main/java/com/google/pubsublite/kafka/sink/PublisherFactory.java
  src/main/java/com/google/pubsublite/kafka/sink/Schemas.java
  src/main/resources/log4j.properties
  src/test/java/it/Base.java
  src/test/java/it/StandaloneIT.java
  src/test/resources/cps-sink-connector-test.properties
  src/test/resources/cps-source-connector-test.properties
  src/test/resources/kafka_vm_startup_script.sh
  src/test/resources/pubsub-lite-sink-connector-test.properties
  src/test/resources/pubsub-lite-source-connector-test.properties
  versions.txt
Labels: size: l

#129 test: Fix tearDown, add reservations in StandaloneIT
  src/test/java/it/StandaloneIT.java
Labels: automerge, size: m

#130 chore: enable continuous test and readme fixes
  .kokoro/continuous/integration.cfg
  README.md
Labels: size: s

#131 chore: Update deps
  pom.xml
Labels: size: s

#135 fix: add parent in pom.xml
  pom.xml
  src/main/java/com/google/pubsub/kafka/common/ConnectorCredentialsProvider.java
  src/main/java/com/google/pubsub/kafka/common/ConnectorUtils.java
  src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkConnector.java
  src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java
  src/main/java/com/google/pubsub/kafka/source/AckBatchingSubscriber.java
  src/main/java/com/google/pubsub/kafka/source/CloudPubSubGRPCSubscriber.java
  src/main/java/com/google/pubsub/kafka/source/CloudPubSubRoundRobinSubscriber.java
  src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnector.java
  src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
  src/main/java/com/google/pubsub/kafka/source/CloudPubSubSubscriber.java
  src/main/java/com/google/pubsub/kafka/source/StreamingPullSubscriberFactory.java
  src/test/java/com/google/pubsub/kafka/sink/CloudPubSubSinkConnectorTest.java
  src/test/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTaskTest.java
  src/test/java/com/google/pubsub/kafka/source/AckBatchingSubscriberTest.java
  src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnectorTest.java
  src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java
  src/test/java/com/google/pubsub/kafka/source/StreamingPullSubscriberTest.java
  src/test/java/com/google/pubsublite/kafka/sink/PubSubLiteSinkTaskTest.java
  src/test/java/com/google/pubsublite/kafka/sink/SchemasTest.java
  src/test/java/com/google/pubsublite/kafka/source/PollerImplTest.java
  src/test/java/com/google/pubsublite/kafka/source/PubSubLiteSourceTaskTest.java
Labels: size: l

#140 fix: update version in pom and readme
  README.md
  pom.xml
Labels: size: xs

#144 docs: add auth info and add annotation
  README.md
  pom.xml
Labels: size: xs
