Repository googleapis/java-pubsub-group-kafka-connector, pull requests merged in 2022-07, with the labels that each got.

#23 chore: update kokoro build configs
  .kokoro/common.cfg
  .kokoro/common.sh
  .kokoro/continuous/common.cfg
  .kokoro/nightly/common.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/release/bump_snapshot.cfg
  .kokoro/release/common.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.cfg
  .kokoro/release/drop.sh
  .kokoro/release/promote.cfg
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/snapshot.cfg
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  pom.xml
Labels: size: m

#26 chore: fix lint and update codeowners
  .github/CODEOWNERS
  .kokoro/build.sh
  src/main/java/com/google/pubsub/kafka/source/AckBatchingSubscriber.java
  src/test/java/com/google/pubsublite/kafka/sink/PubSubLiteSinkTaskTest.java
Labels: size: s

#28 chore: add version.txt
  pom.xml
  versions.txt
Labels: size: xs

#31 chore: update sync repo settings
  .github/sync-repo-settings.yaml
Labels: size: s

#32 chore: support windows longpaths
  .github/workflows/ci.yaml
Labels: size: xs

#33 chore: add repo metadata file
  .repo-metadata.json
Labels: size: s

#35 chore: reformat .repo-metadata.json and update owlbot.py
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto-label.yaml
  .github/blunderbuss.yml
  .kokoro/coerce_logs.sh
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/populate-secrets.sh
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  .repo-metadata.json
  CONTRIBUTING.md
  owlbot.py
  renovate.json
Labels: size: m

#46 deps: Add and remove dependencies based on dependencies.sh output
  pom.xml
  src/test/java/com/google/pubsub/kafka/source/AckBatchingSubscriberTest.java
Labels: size: m

#5 deps: Increment major version of Kafka Client dependency to 3.2.0
  copy_tool.py
  pom.xml
Labels: size: xs

#61 test: add IT (phase I) for standalone Kafka cluster
  .kokoro/build.sh
  .kokoro/presubmit/integration.cfg
  config/cps-sink-connector.properties
  config/cps-source-connector.properties
  config/pubsub-lite-sink-connector.properties
  config/pubsub-lite-source-connector.properties
  pom.xml
  src/test/java/it/Base.java
  src/test/java/it/StandaloneIT.java
Labels: size: l
